/**
 * A CITY'S ISLAND. Every city opens as its own island of cells, generated by
 * Sandbox 1's generator from a seed that comes from the city's card on the
 * planet — so a city is always the same island, in the browser and in the API.
 */
import { generateMap, WATER_BIOME, type HexTile } from './hexmap'

/** The island seed of a planet card: stable, spread out, never zero. */
export const islandSeed = (tile: number) => ((Math.imul(tile + 1, 2654435761) >>> 0) % 999_983) + 1

/** A cell takes a settlement if it is land and no part of it is water. */
export const buildable = (t: Pick<HexTile, 'kind' | 'biomes'>) => t.kind === 'LAND' && t.biomes.every((b) => b !== WATER_BIOME)

export const cellKey = (t: Pick<HexTile, 'q' | 'r'>) => `${t.q},${t.r}`

const islands = new Map<number, Map<string, HexTile>>()
/** The island's cells by "q,r". Generating one takes a moment, so the last few are kept. */
export function islandCells(seed: number): Map<string, HexTile> {
	let cells = islands.get(seed)
	if (!cells) {
		cells = new Map(generateMap(seed).tiles.map((t) => [cellKey(t), t]))
		islands.set(seed, cells)
		if (islands.size > 8) islands.delete(islands.keys().next().value!)
	}
	return cells
}

/** A settlement's level from its headcount: one for every Fibonacci number reached, up to 233. */
export { villageLevel as settlementLevel } from './villages'
